#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0x00775759
yabai -m config normal_window_border_color   0x00505050
yabai -m config insert_window_border_color   0xffd75f5f
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   4

# rules for status windows, so they cannot be moved
yabai -m rule --add title=statuswin manage=off grid=20:20:0:0:5:4
yabai -m rule --add title=musicwin manage=off grid=30:30:16:28:14:2

# yabai -m signal --add event=application_activated action="/Users/Aditya/Desktop/test.sh" app=Spotify 

#yabai -m signal --add event=window_moved title=statuswin \
#     action='yabai -m window $YABAI_WINDOW_ID --grid 20:20:0:0:5:4'

#yabai -m signal --add event=window_resized title=statuswin \
#     action='yabai -m window $YABAI_WINDOW_ID --grid 20:20:0:0:5:4'

echo "yabai configuration loaded.."
